### ISSUE TITLE
Feature request: disable draft mode

### ISSUE THREAD

**Issue by dur41d** [forestryio/forestry.io#100]
I would like the ability to disable draft mode and publish with one-click as it simplifies my editing.

**Comment by Germoe** [comment]
Hey, thanks for your request.

We're not monitoring Github issues for feature requests. But are happy to discuss and take note of your feature request through the in-app support chat, [email](https://forestry.io/support/) or [our Slack Community channel](https://join.slack.com/t/forestry-community/shared_invite/enQtNDAxMTU5NzcwMzA3LWUyYTk3NDY2ZDNiMjFhNmVlMjExM2FjYzFhNjJhNjU2NTc2ODVjZTdlYjJiODhhZDgwYTVhYjY0ZGU3ZWFmYzM). 

I saw that you already joined our Slack channel to request this feature so you're all set.

Thanks 👋
