### ISSUE TITLE
Showcase submission

### ISSUE THREAD

**Issue by monsieurnebo** [forestryio/forestry.io#164]
- **Title**: Hapticmedia Blog
- **Image**: [Click 📸](https://d33wubrfki0l68.cloudfront.net/54f101cc77f506e3f06523115e14ce63922d25e2/1221d/showcase/hapticmedia/featured_hu4e9c0830eabb70b93572090b79da0c5d_543922_1024x512_fill_catmullrom_top_2.png) 
- **Permalink**: https://hapticmedia.fr/blog/en/

We would be happy to contribute to spreading Forestry.io into the world (as we did for [GoHugo](https://gohugo.io/showcase/hapticmedia/)) 🙏

CC @DirtyF

**Comment by DirtyF** [comment]
Bonjour, désolé pour la réponse tardive, votre site vient d'être ajouté sur notre showcase: https://forestry.io/showcase/

Merci de l'avoir soumis. 😉
