### ISSUE TITLE
Pharmaseal.co showcase request

### ISSUE THREAD

**Issue by jonoroboto** [forestryio/forestry.io#183]
Hi @teamforestry

Just thought I'd drop a request to get Pharmaseal listed within the showcase on Forestry. They've been [showcased previously on HUGO](https://gohugo.io/showcase/pharmaseal/) and they're great believers in the Forestry CMS.

We'd love to see them on Forestry, and they're really making waves in the pharmaceutical industry. If you require any media/mockups from our side, please drop me a message on Slack @jono

![pharmaseal co](https://user-images.githubusercontent.com/29231011/72159931-510b1780-33b5-11ea-8ee9-48420cdba1c7.png)

**Comment by DirtyF** [comment]
Site added on https://forestry.io/showcase/
