### ISSUE TITLE
Docs: add Netlify as deploy option?

### ISSUE THREAD

**Issue by sw-yx** [forestryio/forestry.io#187]
hi! was browsing the docs https://forestry.io/docs/hosting/ and realized they dont include Netlify as an option. would you be open to a PR adding it? any preferred format or pointers that you might want to include?

**Comment by DirtyF** [comment]
Hi @sw-yx, we'll gladly accept a PR, we've been recommending Netlify to our customers [as a deployment solution](https://forestry.io/docs/sunset/deployments/), somehow we didn't update our hosting guide 😊

**Comment by DirtyF** [comment]
These options were the ones we were supporting until now, we'll have to rewrite this guide, so a brief description of your service, and pointers to any guide or documentation that miight help our customers will be helpful. 🙏

**Comment by DirtyF** [comment]
@sw-yx Don't bother, I'll just list deployments options on hosting page.

**Comment by DirtyF** [comment]
Done.

**Comment by sw-yx** [comment]
that was fast!

**Comment by DirtyF** [comment]
@sw-yx you made me do it 😄
