### ISSUE TITLE
Docs: Add alternative to gatsby-remark-normalize-paths 

### ISSUE THREAD

**Issue by rohit-gohri** [forestryio/forestry.io#198]
I am currently in the process of making a Gatsby site with Forestry. And I was stuck trying to get absolute paths working with `gatsby-image` and sharp transformer.

I followed the docs at https://forestry.io/docs/guides/developing-with-gatsby/#forestry-doesn-t-like-relative-image-urls-gatsby-prefers-them and tried `gatsby-remark-normalize-paths` but it didn't work for me. I also tried foresty's fork https://github.com/forestryio/gatsby-remark-normalize-paths/ but that also didn't work.

I think it could be related to https://github.com/gatsbyjs/gatsby/issues/19876

Anyway I tried `gatsby-remark-relative-images` after that and it worked for me. Maybe that can be added to the docs too?

You can view how I am using it at https://github.com/rohit-gohri/blog/tree/next

**Comment by DirtyF** [comment]
Hey, thanks for the feedback, it would be a good addition, do you have any public example?
