### ISSUE TITLE
[Github Pages][Hugo] Custom domain not being respected by Forestry

### ISSUE THREAD

**Issue by ncphillips** [forestryio/forestry.io#20]
This happens with Hugo sites. Github Pages puts the CNAME folder in the root of the project, but Hugo doesn't copy files from the root to the built site. All you need to do is put the CNAME in the `static` directory.

**Comment by chekalskiy** [comment]
Any updates on that?

**Comment by ncphillips** [comment]
@chekalskiy This is a note to add a doc to the website. The solution is in the comment.
