### ISSUE TITLE
Showcase request: MadeBySphere

### ISSUE THREAD

**Issue by chrisjingram** [forestryio/forestry.io#202]
We're a web design agency from Hackney in London, and we just launched our new site. We're big believers in JAMstack and use Forestry for all of our websites.

I'd love for us to be in the showcase!

Website: https://madebysphere.com

Thanks!

**Comment by DirtyF** [comment]
Here you are Sir. 🇬🇧 🎩 🍵

<img width="500" alt="showcase-update" src="https://user-images.githubusercontent.com/103008/81948881-81ccb900-9602-11ea-8fbc-932f77de1406.png">

**Comment by chrisjingram** [comment]
Thanks, appreciate it!
