### ISSUE TITLE
Submission: Andrew Boardman (a personal blog and portfolio site)

### ISSUE THREAD

**Issue by manoverboard** [forestryio/forestry.io#210]
This is a personal blog and portfolio site built with Jekyll and Forestry, which we love. 

Thank you for your consideration!

<img width="1281" alt="Screen Shot 2020-05-21 at 1 57 17 PM" src="https://user-images.githubusercontent.com/157909/82595374-17b89480-9b6b-11ea-87ae-27a5c9d0d351.png">

**Comment by DirtyF** [comment]
Hi Andrew, thanks for the submission, we mostly feature company websites in our showcase, feel free to share if you use Forestry for work.

**Comment by manoverboard** [comment]
Hi - okay that makes sense. Actually, we're about to build a site using Forestry for a large, prominent client. We are a design studio in Winnipeg - I wonder if you have any agency partnerships? We are pushing Forestry from here out. :)
