### ISSUE TITLE
feature request: make frontmatter div resizable/hidable

### ISSUE THREAD

**Issue by kotgakapainor** [forestryio/forestry.io#217]
### Description
When working with the big content field on the right side the chance is high that you dont need to see the frontmatter fields on the left the whole time. As not everybody has an ultrawide screen roughly 50% of the screen is cluttered with unnecessary meta fields. Especially content writers who depend on forestry dont actually need to see the fields at all.

### Steps to reproduce

1. Grab a Laptop / resize window to <= 1200px
2. Go to forestry.io
3. Open a document with the Frontmatter Template:  Fields and big content area

### Expected result

One of the following:

- Resizable Container
- Toggleto make the content area full width
- Setting to change the Frontmatter Template to vertically stacked containers instead of horizontally stacked
- Static html classes on the containers, for me to sideload my own custom sollution

![Anmerkung 2020-07-30 125804](https://user-images.githubusercontent.com/17276816/88915437-8e0cfd80-d264-11ea-9ee0-bd211eb5e377.png)

### Actual result

no of the above mentioned options

**Comment by DirtyF** [comment]
Hi @kotgakapainor this is our website repository, please visit https://portal.productboard.com/forestry to vote or suggest for features. (e.g https://portal.productboard.com/forestry/1-forestry-io-roadmap/c/56-focus-mode)

We don't have any plan to change the current UI at the moment, we made it responsive on purpose to support a broad range of devices.

You can always resize the window to a smaller viewport to trigger a more focused view: 
https://twitter.com/FrankTldr/status/1252202321490202626/photo/2

One of our users developed a chrome extension to work around that limitation (not officially supported by maybe it can help you)
https://chrome.google.com/webstore/detail/forestry-desktop-enhancer/ggbhcjgmaopfendjalgaikmpjchcebfb

Thanks for your feedback 🙏
