### ISSUE TITLE
Favicon isn't visible on dark background

### ISSUE THREAD

**Issue by mitchmac** [forestryio/forestry.io#221]
When the Forestry favicon is displayed on a dark background, it can be difficult/impossible to see and can result in losing browser tab context.

**Comment by spbyrne** [comment]
We could probably just add a white background? Would still look the same for light browsers.

**Comment by DirtyF** [comment]
https://realfavicongenerator.net/favicon_checker?protocol=http&site=forestry.io

**Comment by DirtyF** [comment]
Favicons updated with a white background as suggested:

<img width="677" alt="Capture d’écran 2020-08-14 à 20 55 57" src="https://user-images.githubusercontent.com/103008/90283836-30d29800-de71-11ea-972f-b9bf401e117f.png">
