### ISSUE TITLE
Docs: https://forestry.io/docs/troubleshooting/cname/

### ISSUE THREAD

**Issue by fakepilot** [forestryio/forestry.io#222]
Hello,

I am using Jekyll and Forestry.io with Github Pages. When I commit and sync locally, it works. But whenever Forestry.io makes a push, it always  removes the CNAME file. If it's placed in the main branch, it does not move and the site breaks. If it's in gh-pages, then Forestry deploys and destroys it.

Have tried putting a .gitignore with CNAME in the gh-pages, tried having the NAME in source folder and branch, tried having it in _site that gets pushed to gh-pages... Not sure what to do?

**Comment by DirtyF** [comment]
@fakepilot We should probably archive this page, as we don't deploy to GitHub Pages anymore.
Forestry only pushed back to your source branch.
https://forestry.io/docs/hosting/

Do you have an example to share where Forestry would remove a CNAME file from your repo?

See also https://docs.github.com/en/github/working-with-github-pages/troubleshooting-custom-domains-and-github-pages

**Comment by DirtyF** [comment]
Looking at your commit history, it's unrelated to Foresttry, you added CNAME in your.gitignore and now it's not present.

**Comment by fakepilot** [comment]
Thanks for the fast replies! I followed a Forestry doc Github Actions workflow to get the rep to publish to Github Pages (gh-pages) branch, with Rake gem. Since Pages does not support some plugins and latest version, I needed to do it this way to continue with that theme.

I created a CNAME and .gitignore CNAME on Github, in the gh-pages branch thinking that would keep it from being deleted.
