### ISSUE TITLE
User registered via GitHub account not deleted properly on forestry.io

### ISSUE THREAD

**Issue by pduchnovsky** [forestryio/forestry.io#247]
According to this: https://forestry.io/docs/changelog/2020-04-16-changelog/
This should've been fixed:
"**Properly erase users and sites. This allows former deleted accounts to recreate an account if needed.**"

But it seems it isn't, recently I deleted my account which was registered using GitHub
Now I cannot re-use email or register again
This is the error:
![image](https://user-images.githubusercontent.com/54581833/100526980-59875f00-31ce-11eb-90ee-e4e93fc5b655.png)

**Comment by DirtyF** [comment]
Fixed through support, the former account wasn't properly deleted.
