### ISSUE TITLE
[Feature]? Sidebar hyperlink option?

### ISSUE THREAD

**Issue by liamcharmer** [forestryio/forestry.io#266]
Is it possible for there to be an option to insert a hyperlink into the sidebar? As forestry.io becomes the 'Admin' panel for the website. It would be great to be able to put hyperlinks into the sidebar that go to other services such as analytics. Social media pages etc. All from the same admin panel.

**Comment by DirtyF** [comment]
What you can do is list links in Markdown files and add those Markdown files as document sections in read-only mode. See https://forestry.io/blog/create-in-app-documentation-for-content-editors/

**Comment by liamcharmer** [comment]
@DirtyF Thank you! Sorry I should have read into the blog more and realised this.
