### ISSUE TITLE
Amazon s3

### ISSUE THREAD

**Issue by liamcharmer** [forestryio/forestry.io#267]
Has anyone had any experience integrating Amazon s3 via Digital Ocean Spaces (which is still S3?)

**Comment by DirtyF** [comment]
Hey Liam this is our website repository, please reach out to us through the community Slack. 

We don't plan to support more media providers in Forestry. You'll be able to [create a Media Store with Tina](https://tina.io/docs/media/#creating-a-media-store), our open source CMS library Kit.
