### ISSUE TITLE
How to download Build Files (artifacts)

### ISSUE THREAD

**Issue by surjithctly** [forestryio/forestry.io#82]
Currently, we can publish to FTP, but what if I need to download the build files and upload manually? There is no option. now. 

Please add an option to download Build Files as ZIP.

**Comment by ncphillips** [comment]
Hi @surjithctly we do not track features through these issues. If you would like to request features, please do so through Intercom, or via our [Slack channel](https://forestry.io/blog/join-our-slack-community/).
