### ISSUE TITLE
Deploying gem-based Jekyll theme connected to GitHub repo not working in all cases

### ISSUE THREAD

**Issue by funkfinger** [forestryio/forestry.io#85]
I am seeing different behavior across different Jekyll sites. In one case, the site is able to use a gem-based theme pulled from GitHub, and in another case it is not. It appears as if the `bundle init` command isn't executing in the failed log. This very well could be on my shoulders.

A failing build log:

    Failed to build site

    Installing dependencies
    02:55:55 PM: Started restoring cached node version
    02:55:56 PM: Finished restoring cached node version
    02:55:57 PM: v8.12.0 is already installed.
    02:55:58 PM: Now using node v8.12.0 (npm v6.4.1)
    02:55:58 PM: Attempting ruby version 2.3.6, read from environment
    02:55:58 PM: Using ruby version 2.3.6
    02:55:59 PM: Using PHP version 5.6
    02:55:59 PM: Started restoring cached ruby gems
    02:55:59 PM: Finished restoring cached ruby gems
    02:55:59 PM: Started restoring cached go cache
    02:55:59 PM: Finished restoring cached go cache
    02:55:59 PM: 
    02:55:59 PM: unset GOOS;
    02:55:59 PM: unset GOARCH;
    02:55:59 PM: export GOROOT='/opt/buildhome/.gimme/versions/go1.10.linux.amd64';
    02:55:59 PM: export PATH="/opt/buildhome/.gimme/versions/go1.10.linux.amd64/bin:${PATH}";
    02:55:59 PM: go version >&2;
    02:55:59 PM: 
    02:55:59 PM: export GIMME_ENV='/opt/buildhome/.gimme/env/go1.10.linux.amd64.env';
    02:55:59 PM: go version go1.10 linux/amd64
    02:55:59 PM: Installing missing commands
    02:55:59 PM: Verify run directory
    02:55:59 PM: Executing user command: jekyll build --config config-forestryio.yml --destination _forestry_site
    02:55:59 PM: /opt/buildhome/.rvm/gems/ruby-2.3.6/gems/bundler-1.16.4/lib/bundler/source/git/git_proxy.rb:235:in `allowed_in_path': The git source git://github.com/funkfinger/growing-with-w-theme.git is not yet checked out. Please run `bundle install` before trying to start your application (Bundler::GitError)
    02:55:59 PM: 	from /opt/buildhome/.rvm/gems/ruby-2.3.6/gems/bundler-1.16.4/lib/bundler/source/git/git_proxy.rb:192:in `find_local_revision'
    02:55:59 PM: 	from /opt/buildhome/.rvm/gems/ruby-2.3.6/gems/bundler-1.16.4/lib/bundler/source/git/git_proxy.rb:64:in `revision'
    02:55:59 PM: 	from /opt/buildhome/.rvm/gems/ruby-2.3.6/gems/bundler-1.16.4/lib/bundler/source/git.rb:225:in `revision'
    02:55:59 PM: 	from /opt/buildhome/.rvm/gems/ruby-2.3.6/gems/bundler-1.16.4/lib/bundler/source/git.rb:93:in `install_path'
    02:55:59 PM: 	from /opt/buildhome/.rvm/gems/ruby-2.3.6/gems/bundler-1.16.4/lib/bundler/source/path.rb:126:in `expanded_path'
    02:55:59 PM: 	from /opt/buildhome/.rvm/gems/ruby-2.3.6/gems/bundler-1.16.4/lib/bundler/source/path.rb:163:in `load_spec_files'
    02:55:59 PM: 	from /opt/buildhome/.rvm/gems/ruby-2.3.6/gems/bundler-1.16.4/lib/bundler/source/git.rb:200:in `load_spec_files'
    02:55:59 PM: 	from /opt/buildhome/.rvm/gems/ruby-2.3.6/gems/bundler-1.16.4/lib/bundler/source/path.rb:100:in `local_specs'
    02:55:59 PM: 	from /opt/buildhome/.rvm/gems/ruby-2.3.6/gems/bundler-1.16.4/lib/bundler/source/git.rb:167:in `specs'
    02:55:59 PM: 	from /opt/buildhome/.rvm/gems/ruby-2.3.6/gems/bundler-1.16.4/lib/bundler/definition.rb:754:in `block in converge_locked_specs'
    02:55:59 PM: 	from /opt/buildhome/.rvm/gems/ruby-2.3.6/gems/bundler-1.16.4/lib/bundler/definition.rb:740:in `each'
    02:55:59 PM: 	from /opt/buildhome/.rvm/gems/ruby-2.3.6/gems/bundler-1.16.4/lib/bundler/definition.rb:740:in `converge_locked_specs'
    02:55:59 PM: 	from /opt/buildhome/.rvm/gems/ruby-2.3.6/gems/bundler-1.16.4/lib/bundler/definition.rb:248:in `resolve'
    02:55:59 PM: 	from /opt/buildhome/.rvm/gems/ruby-2.3.6/gems/bundler-1.16.4/lib/bundler/definition.rb:171:in `specs'
    02:55:59 PM: 	from /opt/buildhome/.rvm/gems/ruby-2.3.6/gems/bundler-1.16.4/lib/bundler/definition.rb:238:in `specs_for'
    02:55:59 PM: 	from /opt/buildhome/.rvm/gems/ruby-2.3.6/gems/bundler-1.16.4/lib/bundler/definition.rb:227:in `requested_specs'
    02:55:59 PM: 	from /opt/buildhome/.rvm/gems/ruby-2.3.6/gems/bundler-1.16.4/lib/bundler/runtime.rb:108:in `block in definition_method'
    02:55:59 PM: 	from /opt/buildhome/.rvm/gems/ruby-2.3.6/gems/bundler-1.16.4/lib/bundler/runtime.rb:20:in `setup'
    02:55:59 PM: 	from /opt/buildhome/.rvm/gems/ruby-2.3.6/gems/bundler-1.16.4/lib/bundler.rb:107:in `setup'
    02:55:59 PM: 	from /opt/buildhome/.rvm/gems/ruby-2.3.6/gems/bundler-1.16.4/lib/bundler/setup.rb:20:in `<top (required)>'
    02:55:59 PM: 	from /opt/buildhome/.rvm/rubies/ruby-2.3.6/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    02:55:59 PM: 	from /opt/buildhome/.rvm/rubies/ruby-2.3.6/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    02:55:59 PM: 	from /opt/buildhome/cache/binstubs/jekyll:27:in `<main>'
    02:55:59 PM: Caching artifacts
    02:55:59 PM: Started saving ruby gems
    02:55:59 PM: Finished saving ruby gems
    02:55:59 PM: Started saving pip cache
    02:55:59 PM: Finished saving pip cache
    02:55:59 PM: Started saving emacs cask dependencies
    02:55:59 PM: Finished saving emacs cask dependencies
    02:55:59 PM: Started saving maven dependencies
    02:55:59 PM: Finished saving maven dependencies
    02:55:59 PM: Started saving boot dependencies
    02:55:59 PM: Finished saving boot dependencies
    02:56:00 PM: Started saving go dependencies
    02:56:00 PM: Finished saving go dependencies
    02:56:00 PM: 

a successful build log:

    Installing dependencies
    08:08:20 PM: Downloading and installing node v8.12.0...
    08:08:21 PM: Downloading https://nodejs.org/dist/v8.12.0/node-v8.12.0-linux-x64.tar.xz...
    08:08:21 PM: 
                                                                              0.9%
    ##                                                                         4.1%
    ###########                                                               16.4%
    ########################                                                  34.6%
    #######################################                                   54.6%
    #######################################################                   76.8%
    ######################################################################## 100.0%
    08:08:22 PM: Computing checksum with sha256sum
    08:08:22 PM: Checksums matched!
    08:08:22 PM: Now using node v8.12.0 (npm v6.4.1)
    08:08:24 PM: Attempting ruby version 2.3.6, read from environment
    08:08:24 PM: Using ruby version 2.3.6
    08:08:24 PM: Using PHP version 5.6
    08:08:25 PM: Started restoring cached ruby gems
    08:08:25 PM: Finished restoring cached ruby gems
    08:08:25 PM: Installing gem bundle
    08:08:25 PM: The git source `git://github.com/funkfinger/vigor-cms-theme.git` uses the `git` protocol, which transmits data without encryption. Disable this warning with `bundle config git.allow_insecure true`, or switch to the `https` protocol to keep your data secure.
    08:08:25 PM: Fetching git://github.com/funkfinger/vigor-cms-theme.git
    08:08:25 PM: The dependency tzinfo-data (>= 0) will be unused by any of the platforms Bundler is installing for. Bundler is installing for ruby but the dependency is only for x86-mingw32, x86-mswin32, x64-mingw32, java. To add those platforms to the bundle, run `bundle lock --add-platform x86-mingw32 x86-mswin32 x64-mingw32 java`.
    08:08:25 PM: Fetching gem metadata from https://rubygems.org/...........
    08:08:28 PM: Fetching gem metadata from https://rubygems.org/.
    08:08:28 PM: Resolving dependencies...
    08:08:28 PM: Fetching public_suffix 3.0.3
    08:08:28 PM: Installing public_suffix 3.0.3
    08:08:28 PM: Fetching addressable 2.5.2
    08:08:28 PM: Installing addressable 2.5.2
    08:08:28 PM: Fetching execjs 2.7.0
    08:08:28 PM: Installing execjs 2.7.0
    08:08:28 PM: Fetching autoprefixer-rails 9.1.4
    08:08:28 PM: Installing autoprefixer-rails 9.1.4
    08:08:28 PM: Fetching popper_js 1.14.3
    08:08:28 PM: Installing popper_js 1.14.3
    08:08:28 PM: Fetching rb-fsevent 0.10.3
    08:08:28 PM: Installing rb-fsevent 0.10.3
    08:08:28 PM: Fetching ffi 1.9.25
    08:08:28 PM: Installing ffi 1.9.25 with native extensions
    08:08:28 PM: Fetching rb-inotify 0.9.10
    08:08:34 PM: Installing rb-inotify 0.9.10
    08:08:34 PM: Fetching sass-listen 4.0.0
    08:08:34 PM: Installing sass-listen 4.0.0
    08:08:34 PM: Fetching sass 3.5.7
    08:08:34 PM: Installing sass 3.5.7
    08:08:35 PM: Fetching bootstrap 4.0.0
    08:08:35 PM: Installing bootstrap 4.0.0
    08:08:35 PM: Using bundler 1.16.4
    08:08:35 PM: Fetching colorator 1.1.0
    08:08:35 PM: Installing colorator 1.1.0
    08:08:35 PM: Fetching concurrent-ruby 1.0.5
    08:08:35 PM: Installing concurrent-ruby 1.0.5
    08:08:35 PM: Fetching eventmachine 1.2.7
    08:08:35 PM: Installing eventmachine 1.2.7 with native extensions
    08:08:35 PM: Fetching http_parser.rb 0.6.0
    08:08:45 PM: Installing http_parser.rb 0.6.0 with native extensions
    08:08:45 PM: Fetching em-websocket 0.5.1
    08:08:46 PM: Installing em-websocket 0.5.1
    08:08:46 PM: Fetching forwardable-extended 2.6.0
    08:08:46 PM: Installing forwardable-extended 2.6.0
    08:08:46 PM: Fetching htmlentities 4.3.4
    08:08:46 PM: Installing htmlentities 4.3.4
    08:08:46 PM: Fetching i18n 0.9.5
    08:08:46 PM: Installing i18n 0.9.5
    08:08:46 PM: Fetching jekyll-sass-converter 1.5.2
    08:08:46 PM: Installing jekyll-sass-converter 1.5.2
    08:08:46 PM: Fetching ruby_dep 1.5.0
    08:08:46 PM: Installing ruby_dep 1.5.0
    08:08:46 PM: Fetching listen 3.1.5
    08:08:46 PM: Installing listen 3.1.5
    08:08:46 PM: Fetching jekyll-watch 2.0.0
    08:08:46 PM: Installing jekyll-watch 2.0.0
    08:08:46 PM: Fetching kramdown 1.17.0
    08:08:46 PM: Installing kramdown 1.17.0
    08:08:47 PM: Fetching liquid 4.0.0
    08:08:47 PM: Installing liquid 4.0.0
    08:08:47 PM: Fetching mercenary 0.3.6
    08:08:47 PM: Installing mercenary 0.3.6
    08:08:47 PM: Fetching pathutil 0.16.1
    08:08:47 PM: Installing pathutil 0.16.1
    08:08:47 PM: Fetching rouge 3.2.1
    08:08:47 PM: Installing rouge 3.2.1
    08:08:47 PM: Fetching safe_yaml 1.0.4
    08:08:47 PM: Installing safe_yaml 1.0.4
    08:08:47 PM: Fetching jekyll 3.8.3
    08:08:47 PM: Installing jekyll 3.8.3
    08:08:47 PM: Fetching jekyll-feed 0.11.0
    08:08:47 PM: Installing jekyll-feed 0.11.0
    08:08:47 PM: Fetching jekyll-menus 0.6.0
    08:08:47 PM: Installing jekyll-menus 0.6.0
    08:08:47 PM: Fetching jekyll-redirect-from 0.14.0
    08:08:47 PM: Installing jekyll-redirect-from 0.14.0
    08:08:47 PM: Fetching jekyll-seo-tag 2.5.0
    08:08:47 PM: Installing jekyll-seo-tag 2.5.0
    08:08:48 PM: Fetching jekyll-sitemap 1.2.0
    08:08:48 PM: Installing jekyll-sitemap 1.2.0
    08:08:48 PM: Fetching jekyll_pages_api 0.1.6
    08:08:48 PM: Installing jekyll_pages_api 0.1.6
    08:08:48 PM: Fetching jekyll_pages_api_search 0.5.0
    08:08:48 PM: Installing jekyll_pages_api_search 0.5.0
    08:08:48 PM: Using vigor-cms-theme 0.0.8 (was 0.0.5) from git://github.com/funkfinger/vigor-cms-theme.git (at master@8193b0e)
    08:08:48 PM: Bundle complete! 8 Gemfile dependencies, 39 gems now installed.
    08:08:48 PM: Bundled gems are installed into `/opt/buildhome/cache/bundle`
    08:08:48 PM: Post-install message from sass:
    08:08:48 PM: 
    08:08:48 PM: Ruby Sass is deprecated and will be unmaintained as of 26 March 2019.
    08:08:48 PM: 
    08:08:48 PM: * If you use Sass as a command-line tool, we recommend using Dart Sass, the new
    08:08:48 PM:   primary implementation: https://sass-lang.com/install
    08:08:48 PM: 
    08:08:48 PM: * If you use Sass as a plug-in for a Ruby web framework, we recommend using the
    08:08:48 PM:   sassc gem: https://github.com/sass/sassc-ruby#readme
    08:08:48 PM: 
    08:08:48 PM: * For more details, please refer to the Sass blog:
    08:08:48 PM:   http://sass.logdown.com/posts/7081811
    08:08:48 PM: 
    08:08:48 PM: Gem bundle installed
    08:08:48 PM: Started restoring cached go cache
    08:08:48 PM: Finished restoring cached go cache
    08:08:48 PM: 
    08:08:48 PM: unset GOOS;
    08:08:48 PM: unset GOARCH;
    08:08:48 PM: export GOROOT='/opt/buildhome/.gimme/versions/go1.10.linux.amd64';
    08:08:48 PM: export PATH="/opt/buildhome/.gimme/versions/go1.10.linux.amd64/bin:${PATH}";
    08:08:48 PM: go version >&2;
    08:08:48 PM: 
    08:08:48 PM: export GIMME_ENV='/opt/buildhome/.gimme/env/go1.10.linux.amd64.env';
    08:08:48 PM: go version go1.10 linux/amd64
    08:08:48 PM: Installing missing commands
    08:08:48 PM: Verify run directory
    08:08:48 PM: Executing user command: jekyll build --config config-forestryio.yml --destination _forestry_site
    08:08:48 PM: Configuration file: config-forestryio.yml
    08:08:48 PM:             Source: /opt/buildhome/repo
    08:08:48 PM:        Destination: _forestry_site
    08:08:48 PM:  Incremental build: disabled. Enable with --incremental
    08:08:48 PM:       Generating... 
    08:08:48 PM: jekyll_pages_api_search: checking for Node.js: v8.12.0
    08:08:48 PM:        Jekyll Feed: Generating feed for posts
    08:08:48 PM:                     done in 1.283 seconds.
    08:08:50 PM:  Auto-regeneration: disabled. Use --watch to enable.
    08:08:50 PM: Caching artifacts
    08:08:50 PM: Started saving ruby gems
    08:08:50 PM: Finished saving ruby gems
    08:08:50 PM: Started saving pip cache
    08:08:50 PM: Finished saving pip cache
    08:08:50 PM: Started saving emacs cask dependencies
    08:08:50 PM: Finished saving emacs cask dependencies
    08:08:50 PM: Started saving maven dependencies
    08:08:50 PM: Finished saving maven dependencies
    08:08:50 PM: Started saving boot dependencies
    08:08:50 PM: Finished saving boot dependencies
    08:08:50 PM: Started saving go dependencies
    08:08:50 PM: Finished saving go dependencies
    08:08:50 PM: Cached node version v8.12.0
    08:08:50 PM:

**Comment by funkfinger** [comment]
Things have magically fixed themselves - please close.

**Comment by 2manyprojects2littletime** [comment]
Hi @funkfinger yes the behaviour was initially a little flaky, but should be fixed now.  
This channel isn't actively monitored, for the quickest response time you can bring issues like this to our attention in the in-app support tool or on our community slack.  You can get an invite here: https://forestry.io/blog/join-our-slack-community/
Thanks for taking the time to let us know!
Matt
