### ISSUE TITLE
config.toml

### ISSUE THREAD

**Issue by cece554** [forestryio/forestry.io#91]
Im having trouble connecting my config.toml file to forestry.

heres my folder structure thats connected to git
<img width="174" alt="screen shot 2018-10-06 at 3 21 02 pm" src="https://user-images.githubusercontent.com/3174608/46575498-ba62d600-c97b-11e8-8bb2-56c547ccb1c9.png">

but when i enter the config path sawmill-starter/ 
its says Cannot find config file in specified path.
and the same when i try forestry/

**Comment by ncphillips** [comment]
Hi @cece554 your config is inside `themes`. I suspect it should be in the root folder.

**Comment by ncphillips** [comment]
Note that we do not provide support through Github issues. Please contact us through Intercom, or join our [Community Slack](https://forestry.io/blog/join-our-slack-community/) for support on these kind of issues.
