### ISSUE TITLE
Feature request: Side menu bookmarks

### ISSUE THREAD

**Issue by dur41d** [forestryio/forestry.io#99]
I have a blog like site with hundreds of articles that are organized by categories (or tags). When I edit the magazine it's helpful to be able to navigate quickly to the articles or each category from the side menu.

The section functionality does not fit this use case as I can only filter by the file name. 

I suggest adding the ability to filter by the fields in the search box (e.g. tags:sport) and be able to bookmark this search in the side menu. This way the user can create many views that fit his workflows.

**Comment by Germoe** [comment]
Hey, thanks for your request.

We're not monitoring Github issues for feature requests. But are happy to discuss and take note of your feature request through the in-app support chat, [email](https://forestry.io/support/) or [our Slack Community channel](https://join.slack.com/t/forestry-community/shared_invite/enQtNDAxMTU5NzcwMzA3LWUyYTk3NDY2ZDNiMjFhNmVlMjExM2FjYzFhNjJhNjU2NTc2ODVjZTdlYjJiODhhZDgwYTVhYjY0ZGU3ZWFmYzM). 

I saw that you already joined our Slack channel to request this feature so you're all set.

Thanks 👋
